# Generated by Django 5.2 on 2025-09-28 18:55

import django.core.validators
import django.db.models.deletion
import uuid
import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='artwork_categories/', validators=[vitrine.validators.validate_image_file], verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Artwork Category',
                'verbose_name_plural': 'Artwork Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SouvenirCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='souvenir_categories/', validators=[vitrine.validators.validate_image_file], verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Souvenir Category',
                'verbose_name_plural': 'Souvenir Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço em reais (R$).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.FloatField(verbose_name='Largura (cm)')),
                ('height', models.FloatField(verbose_name='Altura (cm)')),
                ('technique', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica')),
                ('year_created', models.DateField(blank=True, null=True, verbose_name='Ano de criação')),
                ('style', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estilo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='user.artist')),
                ('art_work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='vitrine.artworkcategory')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='artwork/', validators=[vitrine.validators.validate_image_file])),
                ('is_primary', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(help_text='Imagens do produto.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vitrine.artwork')),
            ],
            options={
                'verbose_name': 'Product Image Artwork',
                'verbose_name_plural': 'Product Images Artworks',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', validators=[vitrine.validators.validate_image_file], verbose_name='Imagem')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vitrine.bannergroup')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço em reais (R$).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('size', models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande'), ('Extra Grande', 'Extra Grande')], max_length=20, null=True, verbose_name='Tamanho')),
                ('souvenir_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='vitrine.souvenircategory')),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SouvenirImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='souvenir/', validators=[vitrine.validators.validate_image_file])),
                ('is_primary', models.BooleanField(default=False)),
                ('souvenir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vitrine.souvenir')),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
