# Generated by Django 5.2 on 2025-11-13 22:32

import django.core.validators
import django.db.models.deletion
import uuid
import vitrine.utils
import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='blog/', validators=[vitrine.validators.validate_image_file], verbose_name='Imagem')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefaultAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, validators=[vitrine.utils.validar_cep], verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('number', models.CharField(max_length=100, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço Padrão',
                'verbose_name_plural': 'Endereços Padrão',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_weight', models.FloatField(help_text='Peso total em kg', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso')),
                ('package_width', models.FloatField(help_text='Largura em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largura')),
                ('package_height', models.FloatField(help_text='Altura em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Altura')),
                ('package_length', models.FloatField(help_text='Comprimento em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Comprimento')),
            ],
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['name'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='artworkcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de obras', 'verbose_name_plural': 'Categorias de obras'},
        ),
        migrations.AlterModelOptions(
            name='bannergroup',
            options={'verbose_name': 'Banner Group', 'verbose_name_plural': 'Banner Groups'},
        ),
        migrations.RemoveField(
            model_name='artworkcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artworkcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artworkcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='default_address',
            field=models.ForeignKey(default='Endereço Padrão', on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='vitrine.defaultaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='vitrine.package'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to='vitrine.package'),
        ),
    ]
