# Generated by Django 5.2 on 2025-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['name'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='artworkcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de obras', 'verbose_name_plural': 'Categorias de obras'},
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
