# Generated by Django 5.2 on 2025-10-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_alter_artwork_options_alter_artworkcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
