# Generated by Django 5.2 on 2025-11-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_blog_defaultaddress_package_alter_artwork_options_and_more'),
    ]

    operations = [
        
    ]
