# Generated by Django 5.2 on 2025-10-17 19:16

import uuid
import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_alter_bannergroup_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('image', models.ImageField(upload_to='blog/', validators=[vitrine.validators.validate_image_file], verbose_name='Imagem')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bannergroup',
            options={'verbose_name': 'Banner Group', 'verbose_name_plural': 'Banner Groups'},
        ),
    ]
