# Generated by Django 5.2 on 2025-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_blog_alter_bannergroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
