# Generated by Django 5.2 on 2025-10-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artworkcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artworkcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='souvenircategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='artwork',
            name='product_type',
            field=models.CharField(default='artwork', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='product_type',
            field=models.CharField(default='souvenir', editable=False, max_length=20),
        ),
    ]
