# Generated by Django 5.2 on 2025-10-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_remove_artworkcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='souvenir',
            name='product_type',
        ),
    ]
