# Generated by Django 5.2 on 2025-10-23 01:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_remove_artwork_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Peso total em kg', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso')),
                ('width', models.FloatField(help_text='Largura em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largura')),
                ('height', models.FloatField(help_text='Altura em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Altura')),
                ('length', models.FloatField(help_text='Comprimento em cm', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Comprimento')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='vitrine.package'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to='vitrine.package'),
        ),
    ]
