# Generated by Django 5.2 on 2025-11-11 23:06

import django.db.models.deletion
import uuid
import vitrine.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_package_artwork_package_souvenir_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, validators=[vitrine.utils.validar_cep], verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('number', models.CharField(max_length=100, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço Padrão',
                'verbose_name_plural': 'Endereços Padrão',
            },
        ),
        migrations.AddField(
            model_name='souvenir',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='vitrine.defaultaddress'),
        ),
    ]
