# Generated by Django 5.2 on 2025-11-11 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_defaultaddress_souvenir_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='default_address',
            field=models.ForeignKey(default=uuid.UUID('90549436-1bc3-43fa-97fc-a59ab7ae5d07'), on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='vitrine.defaultaddress'),
            preserve_default=False,
        ),
    ]
