# Generated by Django 5.2 on 2025-11-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_defaultaddress_souvenir_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='height',
            new_name='package_height',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='length',
            new_name='package_length',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='weight',
            new_name='package_weight',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='width',
            new_name='package_width',
        ),
    ]
