# Generated by Django 5.2 on 2025-11-24 21:49

import checkout.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrine', '0003_rename_height_package_package_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('total_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço total de frete')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total geral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário')),
                ('shipping_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de frete')),
                ('shipping_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário de frete')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrine.artwork', verbose_name='Obra')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.cart')),
                ('souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrine.souvenir', verbose_name='Souvenir')),
            ],
            options={
                'verbose_name': 'Item do carrinho',
                'verbose_name_plural': 'Itens do carrinho',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(default=checkout.utils.generate_order_code, editable=False, max_length=12, unique=True, verbose_name='Código')),
                ('order_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completo'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Falhou')], default='pending', max_length=15, verbose_name='Status')),
                ('order_payment_method', models.CharField(choices=[('pix', 'PIX'), ('cartão', 'Cartão'), ('boleto', 'Boleto')], max_length=10, verbose_name='Método de Pagamento')),
                ('order_total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço total')),
                ('order_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('order_shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço total de frete')),
                ('order_date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data da compra')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('order_item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='checkout.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_payment_id', models.CharField(max_length=30, verbose_name='ID do Pagamento')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('date_of_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('date_last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cartão', 'Cartão'), ('boleto', 'Boleto')], max_length=30, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('rejeitado', 'Rejeitado')], max_length=12, verbose_name='Status')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='checkout.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-date_created'],
            },
        ),
    ]
