# Generated by Django 5.2 on 2025-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_notification_order_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
