# Generated by Django 5.2 on 2025-11-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_cartitem_options_cartitem_shipping_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
