# Generated by Django 5.2 on 2025-05-11 20:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite um número com DDD. Ex: +55 11 91234-5678', max_length=15, null=True, region=None, unique=True),
        ),
    ]
