# Generated by Django 5.2 on 2025-07-17 01:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_options_user_is_artist_user_is_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Formato: DD/MM/AAAA.', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite um número com DDD. Ex: +55 11 91234-5678', max_length=128, null=True, region='BR', unique=True),
        ),
    ]
