# Generated by Django 5.2 on 2025-07-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_date_of_birth_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wants_to_be_artist',
            field=models.BooleanField(default=False, verbose_name='Quero ser Artista!'),
        ),
    ]
