# Generated by Django 5.2 on 2025-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_artistaddress_state_alter_clientaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistaddress',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você.', null=True, verbose_name='Biografia'),
        ),
    ]
