# Generated by Django 5.2 on 2025-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_artistaddress_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistaddress',
            name='bio',
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você.', null=True, verbose_name='Biografia'),
        ),
    ]
