# Generated by Django 5.2 on 2025-08-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_artistaddress_bio_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='artistaddress',
            name='principal',
            field=models.BooleanField(default=True, help_text='Define este endereço como o principal para entregas.', verbose_name='Endereço Padrão?'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='principal',
            field=models.BooleanField(default=True, help_text='Define este endereço como o principal para entregas.', verbose_name='Endereço Padrão?'),
        ),
    ]
