# Generated by Django 5.2 on 2025-08-10 20:14

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_artistaddress_complement_clientaddress_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaddress',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[user.models.validar_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[user.models.validar_cep], verbose_name='CEP'),
        ),
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='user.artist')),
            ],
        ),
    ]
