# Generated by Django 5.2 on 2025-08-10 20:15

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_artistaddress_cep_alter_clientaddress_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaddress',
            name='cep',
            field=models.CharField(max_length=9, validators=[user.models.validar_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='cep',
            field=models.CharField(max_length=9, validators=[user.models.validar_cep], verbose_name='CEP'),
        ),
    ]
