# Generated by Django 5.2 on 2025-08-11 00:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_artistaddress_cep_alter_clientaddress_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, default='artist_banners/default.jpg', help_text='Formato de arquivo: jpg, jpeg ou png.', null=True, upload_to='artist_banners/', validators=[user.models.validate_image_file]),
        ),
    ]
