# Generated by Django 5.2 on 2025-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_artist_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, help_text='Link do seu perfil no Facebook.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link do seu perfil no Instagram.', max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Link do seu perfil no TikTok.', max_length=255, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, help_text='Link do seu perfil no Twitter.', max_length=255, null=True, verbose_name='Twitter'),
        ),
    ]
