# Generated by Django 5.2 on 2025-09-25 19:32

import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_artist_facebook_artist_instagram_artist_tiktok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, default='default/banner.jpg', help_text='Formato de arquivo: jpg, jpeg ou png.', null=True, upload_to='artist_banners/', validators=[vitrine.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default/user_img.jpg', help_text='Formato de arquivo: jpg, jpeg ou png.', null=True, upload_to='photos/', validators=[vitrine.validators.validate_image_file]),
        ),
    ]
