# Generated by Django 5.2 on 2025-09-26 19:07

import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_artist_banner_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitions',
            options={'ordering': ['-date'], 'verbose_name': 'Exposição', 'verbose_name_plural': 'Exposição'},
        ),
        migrations.RemoveField(
            model_name='exhibitions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exhibitions',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='exhibition_banner',
            field=models.ImageField(default='exhibition banners', help_text='Formato de arquivo: jpg, jpeg ou png.', upload_to='exhibition_banners/', validators=[vitrine.validators.validate_image_file]),
        ),
    ]
