# Generated by Django 5.2 on 2025-09-27 15:41

import vitrine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_exhibitions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='description',
            field=models.TextField(default='Sem descrição', help_text='Conte um pouco sobre a exposição.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='exhibition_banner',
            field=models.ImageField(default='default/exhibitions_banner.jpg', help_text='Formato de arquivo: jpg, jpeg ou png.', upload_to='exhibition_banners/', validators=[vitrine.validators.validate_image_file]),
        ),
    ]
